# Generated by Django 4.2.2 on 2023-07-30 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_name_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="productline",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productline",
            name="weight",
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productline",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
