# Generated by Django 4.2.2 on 2023-07-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_productline_created_at_productline_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="productline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_image",
                to="product.productline",
            ),
        ),
    ]
